const myApps = [
    { name: "Samsung Discover", pkg: "android.autoinstalls.config.samsung" },
    { name: "Amazon App Manager", pkg: "com.amazon.appmanager" },
    { name: "Amazon Video Client", pkg: "com.amazon.avod.thirdpartyclient" },
    { name: "Amazon Freevee", pkg: "com.amazon.fv" },
    { name: "Amazon Kindle", pkg: "com.amazon.kindle" },
    { name: "Amazon MP3", pkg: "com.amazon.mp3" },
    { name: "Amazon Shopping", pkg: "com.amazon.mShop.android" },
    { name: "Amazon Shopping (Global)", pkg: "com.amazon.mShop.android.shopping" },
    { name: "Amazon Appstore", pkg: "com.amazon.venezia" },
    { name: "Android Tags", pkg: "com.android.apps.tag" },
    { name: "Backup Confirm", pkg: "com.android.backupconfirm" },
    { name: "Default Print Service", pkg: "com.android.bips" },
    { name: "WOMA Config", pkg: "com.android.bipscom.wsomacp" },
    { name: "Bluetooth MIDI Service", pkg: "com.android.bluetoothmidiservice" },
    { name: "Bookmark Provider", pkg: "com.android.bookmarkprovider" },
    { name: "Call Log Backup", pkg: "com.android.calllogbackup" },
    { name: "Carrier Default App", pkg: "com.android.carrierdefaultapp" },
    { name: "Chrome", pkg: "com.android.chrome" },
    { name: "CTS Shim", pkg: "com.android.cts.ctsshim" },
    { name: "Basic Daydreams", pkg: "com.android.dreams.basic" },
    { name: "Photo Table Daydream", pkg: "com.android.dreams.phototable" },
    { name: "Dynamic System Updates", pkg: "com.android.dynsystem" },
    { name: "Android Easter Egg", pkg: "com.android.egg" },
    { name: "Samsung Email", pkg: "com.android.email" },
    { name: "Emergency Alerts", pkg: "com.android.emergency" },
    { name: "Exchange Services", pkg: "com.android.exchange" },
    { name: "Hotspot 2.0 Login", pkg: "com.android.hotspot2" },
    { name: "Ok Google Enrollment", pkg: "com.android.hotwordenrollment.okgoogle" },
    { name: "Google Enrollment (T)", pkg: "com.android.hotwordenrollment.tgoogle" },
    { name: "Google Enrollment (X)", pkg: "com.android.hotwordenrollment.xgoogle" },
    { name: "HTML Viewer", pkg: "com.android.htmlviewer" },
    { name: "Display Cutout (Corner)", pkg: "com.android.internal.display.cutout.emulation.corner" },
    { name: "Display Cutout (Double)", pkg: "com.android.internal.display.cutout.emulation.double" },
    { name: "Display Cutout (Hole)", pkg: "com.android.internal.display.cutout.emulation.hole" },
    { name: "Display Cutout (Tall)", pkg: "com.android.internal.display.cutout.emulation.tall" },
    { name: "Display Cutout (Waterfall)", pkg: "com.android.internal.display.cutout.emulation.waterfall" },
    { name: "One-Handed Mode Gesture", pkg: "com.android.internal.systemui.onehanded.gestural" },
    { name: "Work Setup", pkg: "com.android.managedprovisioning" },
    { name: "Print Spooler", pkg: "com.android.printspooler" },
    { name: "Google Calendar Sync", pkg: "com.android.providers.calendar" },
    { name: "Partner Bookmarks", pkg: "com.android.providers.partnerbookmarks" },
    { name: "User Dictionary", pkg: "com.android.providers.userdictionary" },
    { name: "Notes Role Service", pkg: "com.android.role.notes.enabled" },
    { name: "Settings Intelligence", pkg: "com.android.settings.intelligence" },
    { name: "Shared Storage Backup", pkg: "com.android.sharedstoragebackup" },
    { name: "Intent Filter Verification", pkg: "com.android.statementservice" },
    { name: "SIM Toolkit 1", pkg: "com.android.stk" },
    { name: "SIM Toolkit 2", pkg: "com.android.stk2" },
    { name: "System Tracing", pkg: "com.android.traceur" },
    { name: "Live Wallpaper Picker", pkg: "com.android.wallpaper.livepicker" },
    { name: "Wallpaper Backup", pkg: "com.android.wallpaperbackup" },
    { name: "Wallpaper Cropper", pkg: "com.android.wallpapercropper" },
    { name: "Audible", pkg: "com.audible.application" },
    { name: "Samsung Discover (Old)", pkg: "com.aura.oobe.samsung" },
    { name: "Samsung Discover (Global)", pkg: "com.aura.oobe.samsung.gl" },
    { name: "Blurb Checkout", pkg: "com.blurb.checkout" },
    { name: "Booking.com", pkg: "com.booking" },
    { name: "Booking Aid Provider", pkg: "com.booking.aidprovider" },
    { name: "Cequint Caller ID", pkg: "com.cequint.ecid" },
    { name: "CNN Edge Panel", pkg: "com.cnn.mobile.android.phone.edgepanel" },
    { name: "Samsung Dictionary", pkg: "com.diotek.sec.lookup.dictionary" },
    { name: "ANT+ Plugins", pkg: "com.dsi.ant.plugins.antplus" },
    { name: "ANT+ Sample", pkg: "com.dsi.ant.sample.acquirechannels" },
    { name: "ANT+ HAL Service", pkg: "com.dsi.ant.server" },
    { name: "ANT+ Radio Service", pkg: "com.dsi.ant.service.socket" },
    { name: "Game Service Enhance", pkg: "com.enhance.gameservice" },
    { name: "Eterno", pkg: "com.eterno" },
    { name: "DailyHunt Short Videos", pkg: "com.eterno.shortvideos" },
    { name: "Facebook App Manager", pkg: "com.facebook.appmanager" },
    { name: "Facebook App", pkg: "com.facebook.katana" },
    { name: "Facebook Services", pkg: "com.facebook.services" },
    { name: "Facebook System Installer", pkg: "com.facebook.system" },
    { name: "Flipboard App", pkg: "com.flipboard.app" },
    { name: "Flipboard Briefing", pkg: "flipboard.boxer.app" },
    { name: "Google Ad Services", pkg: "com.google.android.adservices.api" },
    { name: "Google AI Core", pkg: "com.google.android.aicore" },
    { name: "Voice Access", pkg: "com.google.android.apps.accessibility.voiceaccess" },
    { name: "AI Wallpapers", pkg: "com.google.android.apps.aiwallpapers" },
    { name: "Google Bard (Gemini)", pkg: "com.google.android.apps.bard" },
    { name: "Google Play Books", pkg: "com.google.android.apps.books" },
    { name: "Google Carrier WiFi", pkg: "com.google.android.apps.carrier.carrierwifi" },
    { name: "Google Docs/Drive", pkg: "com.google.android.apps.docs" },
    { name: "Google Connected Services", pkg: "com.google.android.apps.gcs" },
    { name: "Google Assistant", pkg: "com.google.android.apps.googleassistant" },
    { name: "Google Play Magazines", pkg: "com.google.android.apps.magazines" },
    { name: "Google Maps", pkg: "com.google.android.apps.maps" },
    { name: "Google Messages", pkg: "com.google.android.apps.messaging" },
    { name: "Google Photos", pkg: "com.google.android.apps.photos" },
    { name: "Google Plus", pkg: "com.google.android.apps.plus" },
    { name: "Google Data Restore", pkg: "com.google.android.apps.restore" },
    { name: "Search Selector", pkg: "com.google.android.apps.setupwizard.searchselector" },
    { name: "Google Duo / Meet", pkg: "com.google.android.apps.tachyon" },
    { name: "Device Personalization (Turbo)", pkg: "com.google.android.apps.turbo" },
    { name: "Digital Wellbeing", pkg: "com.google.android.apps.wellbeing" },
    { name: "YouTube Music", pkg: "com.google.android.apps.youtube.music" },
    { name: "Google System Intelligence", pkg: "com.google.android.as" },
    { name: "Private Compute Services", pkg: "com.google.android.as.oss" },
    { name: "Cell Broadcast", pkg: "com.google.android.cellbroadcastreceiver" },
    { name: "Config Updater", pkg: "com.google.android.configupdater" },
    { name: "Android Shared Library", pkg: "com.google.android.ext.shared" },
    { name: "Market Feedback", pkg: "com.google.android.feedback" },
    { name: "Gmail", pkg: "com.google.android.gm" },
    { name: "Google Location History", pkg: "com.google.android.gms.location.history" },
    { name: "Parental Controls", pkg: "com.google.android.gms.supervision" },
    { name: "Google Search", pkg: "com.google.android.googlequicksearchbox" },
    { name: "Health Connect Backup", pkg: "com.google.android.health.connect.backuprestore" },
    { name: "Health Connect Controller", pkg: "com.google.android.healthconnect.controller" },
    { name: "On-Device Personalization", pkg: "com.google.android.ondevicepersonalization.services" },
    { name: "Google Initializer", pkg: "com.google.android.onetimeinitializer" },
    { name: "Extension Overlay", pkg: "com.google.android.overlay.modules.ext.services" },
    { name: "Partner Setup", pkg: "com.google.android.partnersetup" },
    { name: "Print Service Recommendation", pkg: "com.google.android.printservice.recommendation" },
    { name: "Android Auto", pkg: "com.google.android.projection.gearhead" },
    { name: "Safety Center Resources", pkg: "com.google.android.safetycenter.resources" },
    { name: "Google Setup Wizard", pkg: "com.google.android.setupwizard" },
    { name: "Calendar Sync", pkg: "com.google.android.syncadapters.calendar" },
    { name: "Contacts Sync", pkg: "com.google.android.syncadapters.contacts" },
    { name: "Google Hangouts", pkg: "com.google.android.talk" },
    { name: "Speech Services by Google", pkg: "com.google.android.tts" },
    { name: "Google Play Movies & TV", pkg: "com.google.android.videos" },
    { name: "YouTube", pkg: "com.google.android.youtube" },
    { name: "AR Core", pkg: "com.google.ar.core" },
    { name: "Live Transcribe", pkg: "com.google.audio.hearing.visualization.accessibility.scribe" },
    { name: "Mainline Telemetry", pkg: "com.google.mainline.telemetry" },
    { name: "VR Core", pkg: "com.google.vr.vrcore" },
    { name: "NFL Mobile", pkg: "com.gotv.nflgamecenter.us.lite" },
    { name: "Hancom Office Editor", pkg: "com.hancom.office.editor.hidden" },
    { name: "Hiya Smart Call", pkg: "com.hiya.star" },
    { name: "IMDb", pkg: "com.imdb.mobile" },
    { name: "Polaris Office 5", pkg: "com.infraware.polarisoffice5" },
    { name: "Instagram", pkg: "com.instagram.android" },
    { name: "Knox VPN Proxy", pkg: "com.knox.vpn.proxyhandler" },
    { name: "LinkedIn", pkg: "com.linkedin.android" },
    { name: "Microsoft Link to Windows", pkg: "com.microsoft.appmanager" },
    { name: "Excel", pkg: "com.microsoft.office.excel" },
    { name: "Office Hub", pkg: "com.microsoft.office.officehubrow" },
    { name: "Outlook", pkg: "com.microsoft.office.outlook" },
    { name: "PowerPoint", pkg: "com.microsoft.office.powerpoint" },
    { name: "Word", pkg: "com.microsoft.office.word" },
    { name: "OneDrive", pkg: "com.microsoft.skydrive" },
    { name: "Barcode Service", pkg: "com.mobeam.barcodeService" },
    { name: "ChocoEukor Font", pkg: "com.monotype.android.font.chococooky" },
    { name: "Cool Jazz Font", pkg: "com.monotype.android.font.cooljazz" },
    { name: "Foundation Font", pkg: "com.monotype.android.font.foundation" },
    { name: "Rosemary Font", pkg: "com.monotype.android.font.rosemary" },
    { name: "Samsung One Font", pkg: "com.monotype.android.font.samsungone" },
    { name: "My Galaxy", pkg: "com.mygalaxy" },
    { name: "Netflix", pkg: "com.netflix.mediaclient" },
    { name: "Netflix Activation", pkg: "com.netflix.partner.activation" },
    { name: "Swype Keyboard", pkg: "com.nuance.swype.input" },
    { name: "Samsung Max VPN", pkg: "com.opera.max.oem" },
    { name: "Samsung Account", pkg: "com.osp.app.signin" },
    { name: "Policy Device Manager", pkg: "com.policydm" },
    { name: "Qualcomm Location", pkg: "com.qualcomm.location" },
    { name: "Samsung Text-to-Speech", pkg: "com.samsung.SMT" },
    { name: "German TTS Pack", pkg: "com.samsung.SMT.lang_de_de_f00" },
    { name: "UK English TTS Pack", pkg: "com.samsung.SMT.lang_en_gb_f00" },
    { name: "US English TTS Pack", pkg: "com.samsung.SMT.lang_en_us_l03" },
    { name: "Spanish TTS Pack", pkg: "com.samsung.SMT.lang_es_es_f00" },
    { name: "French TTS Pack", pkg: "com.samsung.SMT.lang_fr_fr_f00" },
    { name: "French TTS Pack (L01)", pkg: "com.samsung.SMT.lang_fr_fr_l01" },
    { name: "Italian TTS Pack", pkg: "com.samsung.SMT.lang_it_it_f00" },
    { name: "Russian TTS Pack", pkg: "com.samsung.SMT.lang_ru_ru_f00" },
    { name: "AASA Service", pkg: "com.samsung.aasaservice" },
    { name: "Samsung TalkBack", pkg: "com.samsung.android.accessibility.talkback" },
    { name: "Samsung AI Core", pkg: "com.samsung.android.aicore" },
    { name: "Air Command Manager", pkg: "com.samsung.android.aircommandmanager" },
    { name: "Device Customization Service", pkg: "com.samsung.android.alive.service" },
    { name: "Quick Share (File)", pkg: "com.samsung.android.allshare.service.fileshare" },
    { name: "Quick Share (Media)", pkg: "com.samsung.android.allshare.service.mediashare" },
    { name: "Advanced Sound Detector", pkg: "com.samsung.android.app.advsounddetector" },
    { name: "Apps Edge", pkg: "com.samsung.android.app.appsedge" },
    { name: "Assistant Menu", pkg: "com.samsung.android.app.assistantmenu" },
    { name: "Face AR Stickers", pkg: "com.samsung.android.app.camera.sticker.facear.preload" },
    { name: "Face AR 3D Stickers", pkg: "com.samsung.android.app.camera.sticker.facear3d.preload" },
    { name: "Face AR Avatar", pkg: "com.samsung.android.app.camera.sticker.facearavatar.preload" },
    { name: "Face AR Frames", pkg: "com.samsung.android.app.camera.sticker.facearframe.preload" },
    { name: "Stamp Stickers", pkg: "com.samsung.android.app.camera.sticker.stamp.preload" },
    { name: "Clipboard Edge", pkg: "com.samsung.android.app.clipboardedge" },
    { name: "Edge Panel Service", pkg: "com.samsung.android.app.cocktailbarservice" },
    { name: "Episodes App", pkg: "com.samsung.android.app.episodes" },
    { name: "Filter Installer", pkg: "com.samsung.android.app.filterinstaller" },
    { name: "Find My Phone", pkg: "com.samsung.android.app.find" },
    { name: "Samsung Finder", pkg: "com.samsung.android.app.galaxyfinder" },
    { name: "Samsung Interpreter", pkg: "com.samsung.android.app.interpreter" },
    { name: "LED Back Cover", pkg: "com.samsung.android.app.ledbackcover" },
    { name: "LED Cover Dream", pkg: "com.samsung.android.app.ledcoverdream" },
    { name: "Samsung Memo", pkg: "com.samsung.android.app.memo" },
    { name: "MirrorLink", pkg: "com.samsung.android.app.mirrorlink" },
    { name: "Samsung Notes", pkg: "com.samsung.android.app.notes" },
    { name: "Notes Add-ons", pkg: "com.samsung.android.app.notes.addons" },
    { name: "OMC Agent", pkg: "com.samsung.android.app.omcagent" },
    { name: "Parental Care", pkg: "com.samsung.android.app.parentalcare" },
    { name: "Reading Glass", pkg: "com.samsung.android.app.readingglass" },
    { name: "Samsung Reminder", pkg: "com.samsung.android.app.reminder" },
    { name: "Bixby Routines", pkg: "com.samsung.android.app.routines" },
    { name: "Samsung Internet Edge", pkg: "com.samsung.android.app.sbrowseredge" },
    { name: "Bixby Settings", pkg: "com.samsung.android.app.settings.bixby" },
    { name: "Share Live", pkg: "com.samsung.android.app.sharelive" },
    { name: "Simple Sharing", pkg: "com.samsung.android.app.simplesharing" },
    { name: "Sketchbook", pkg: "com.samsung.android.app.sketchbook" },
    { name: "Samsung Social", pkg: "com.samsung.android.app.social" },
    { name: "Sound Picker", pkg: "com.samsung.android.app.soundpicker" },
    { name: "Bixby Home Page", pkg: "com.samsung.android.app.spage" },
    { name: "Story Album Widget", pkg: "com.samsung.android.app.storyalbumwidget" },
    { name: "Accessibility Talkback", pkg: "com.samsung.android.app.talkback" },
    { name: "Task Edge", pkg: "com.samsung.android.app.taskedge" },
    { name: "Samsung Tips", pkg: "com.samsung.android.app.tips" },
    { name: "Update Center", pkg: "com.samsung.android.app.updatecenter" },
    { name: "VR Setup Wizard", pkg: "com.samsung.android.app.vrsetupwizardstub" },
    { name: "Watch Manager", pkg: "com.samsung.android.app.watchmanager" },
    { name: "Watch Manager Stub", pkg: "com.samsung.android.app.watchmanagerstub" },
    { name: "Watch with TV", pkg: "com.samsung.android.app.withtv" },
    { name: "Samsung App Separation", pkg: "com.samsung.android.appseparation" },
    { name: "AR Drawing", pkg: "com.samsung.android.ardrawing" },
    { name: "AR Emoji", pkg: "com.samsung.android.aremoji" },
    { name: "AR Emoji Editor", pkg: "com.samsung.android.aremojieditor" },
    { name: "AR Zone", pkg: "com.samsung.android.arzone" },
    { name: "Samsung Auth Framework", pkg: "com.samsung.android.authfw" },
    { name: "Quick Share (Aware)", pkg: "com.samsung.android.aware.service" },
    { name: "BBC Agent", pkg: "com.samsung.android.bbc.bbcagent" },
    { name: "Beacon Manager", pkg: "com.samsung.android.beaconmanager" },
    { name: "Bixby Agent", pkg: "com.samsung.android.bixby.agent" },
    { name: "Bixby Voice Stub", pkg: "com.samsung.android.bixby.agent.dummy" },
    { name: "Bixby Global Action", pkg: "com.samsung.android.bixby.es.globalaction" },
    { name: "Bixby On-Device (US)", pkg: "com.samsung.android.bixby.ondevice.enus" },
    { name: "Bixby On-Device (ES)", pkg: "com.samsung.android.bixby.ondevice.esus" },
    { name: "Bixby On-Device (FR)", pkg: "com.samsung.android.bixby.ondevice.frfr" },
    { name: "Bixby PLM Sync", pkg: "com.samsung.android.bixby.plmsync" },
    { name: "Bixby Service", pkg: "com.samsung.android.bixby.service" },
    { name: "Bixby Voice Input", pkg: "com.samsung.android.bixby.voiceinput" },
    { name: "Bixby Wakeup", pkg: "com.samsung.android.bixby.wakeup" },
    { name: "Bixby Vision Framework", pkg: "com.samsung.android.bixbyvision.framework" },
    { name: "Brightness Backup", pkg: "com.samsung.android.brightnessbackupservice" },
    { name: "Samsung Calendar", pkg: "com.samsung.android.calendar" },
    { name: "Car Key", pkg: "com.samsung.android.carkey" },
    { name: "CID Manager", pkg: "com.samsung.android.cidmanager" },
    { name: "CMFA Framework", pkg: "com.samsung.android.cmfa.framework" },
    { name: "Cold Wallet Service", pkg: "com.samsung.android.coldwalletservice" },
    { name: "Data Agent", pkg: "com.samsung.android.da.daagent" },
    { name: "DBSC", pkg: "com.samsung.android.dbsc" },
    { name: "Digital Key", pkg: "com.samsung.android.dkey" },
    { name: "DLP Service", pkg: "com.samsung.android.dlp.service" },
    { name: "DQ Agent", pkg: "com.samsung.android.dqagent" },
    { name: "Car Mode Stub", pkg: "com.samsung.android.drivelink.stub" },
    { name: "DSMS", pkg: "com.samsung.android.dsms" },
    { name: "Dynamic Lockscreen", pkg: "com.samsung.android.dynamiclock" },
    { name: "Easy Setup", pkg: "com.samsung.android.easysetup" },
    { name: "Samsung Email Provider", pkg: "com.samsung.android.email.provider" },
    { name: "Emoji Updater", pkg: "com.samsung.android.emojiupdater" },
    { name: "Embedded SE", pkg: "com.samsung.android.ese" },
    { name: "Samsung Fast", pkg: "com.samsung.android.fast" },
    { name: "Find My Mobile", pkg: "com.samsung.android.fmm" },
    { name: "Find My Mobile (Alt)", pkg: "com.samsung.android.fmmm" },
    { name: "Samsung Forest", pkg: "com.samsung.android.forest" },
    { name: "Game Launcher", pkg: "com.samsung.android.game.gamehome" },
    { name: "Game Tools", pkg: "com.samsung.android.game.gametools" },
    { name: "Game Optimizing Service", pkg: "com.samsung.android.game.gos" },
    { name: "Game Tuner Thin", pkg: "com.samsung.android.gametuner.thin" },
    { name: "Global Post Proc", pkg: "com.samsung.android.globalpostprocmgr" },
    { name: "Samsung GRU", pkg: "com.samsung.android.gru" },
    { name: "HDM App", pkg: "com.samsung.android.hdmapp" },
    { name: "Gear VR Shell", pkg: "com.samsung.android.hmt.vrshell" },
    { name: "Gear VR Service", pkg: "com.samsung.android.hmt.vrsvc" },
    { name: "Home Mode", pkg: "com.samsung.android.homemode" },
    { name: "Resource Share Storage", pkg: "com.samsung.android.hwresourceshare.storage" },
    { name: "Icecone Keyboard Content", pkg: "com.samsung.android.icecone" },
    { name: "Intelligent Voice", pkg: "com.samsung.android.intellivoiceservice" },
    { name: "Samsung Visit-In", pkg: "com.samsung.android.ipsgeofence" },
    { name: "Keyguard Wallpaper Updater", pkg: "com.samsung.android.keyguardwallpaperupdator" },
    { name: "KG Client", pkg: "com.samsung.android.kgclient" },
    { name: "Kids Installer", pkg: "com.samsung.android.kidsinstaller" },
    { name: "Knox Analytics", pkg: "com.samsung.android.knox.analytics.uploader" },
    { name: "Knox Attestation", pkg: "com.samsung.android.knox.attestation" },
    { name: "Knox Container Agent", pkg: "com.samsung.android.knox.containeragent" },
    { name: "Knox Container Core", pkg: "com.samsung.android.knox.containercore" },
    { name: "Knox KPE Core", pkg: "com.samsung.android.knox.kpecore" },
    { name: "Knox Push Manager", pkg: "com.samsung.android.knox.pushmanager" },
    { name: "Knox ZT Framework", pkg: "com.samsung.android.knox.zt.framework" },
    { name: "Live Effect Service", pkg: "com.samsung.android.liveeffectservice" },
    { name: "Deco Pic Stickers", pkg: "com.samsung.android.livestickers" },
    { name: "Personalization Agent", pkg: "com.samsung.android.mapsagent" },
    { name: "Galaxy Agent", pkg: "com.samsung.android.mateagent" },
    { name: "Samsung MCFDS", pkg: "com.samsung.android.mcfds" },
    { name: "Multiple Connectivity", pkg: "com.samsung.android.mcfserver" },
    { name: "Call & Text on Devices", pkg: "com.samsung.android.mdecservice" },
    { name: "Knox Manage", pkg: "com.samsung.android.mdm" },
    { name: "Media and Devices", pkg: "com.samsung.android.mdx" },
    { name: "MDE Service Framework", pkg: "com.samsung.android.mdx.kit" },
    { name: "MDX Quick Board", pkg: "com.samsung.android.mdx.quickboard" },
    { name: "Samsung Messaging", pkg: "com.samsung.android.messaging" },
    { name: "Galaxy Widget", pkg: "com.samsung.android.mfi" },
    { name: "Samsung Experience", pkg: "com.samsung.android.mobileservice" },
    { name: "WiFi Tips", pkg: "com.samsung.android.net.wifi.wifiguider" },
    { name: "Language Pack (US)", pkg: "com.samsung.android.nmt.apps.t2t.languagepack.enesus" },
    { name: "Language Pack (FR)", pkg: "com.samsung.android.nmt.apps.t2t.languagepack.enfr" },
    { name: "Offline Language Model", pkg: "com.samsung.android.offline.languagemodel" },
    { name: "Samsung SmartThings", pkg: "com.samsung.android.oneconnect" },
    { name: "Peripheral Framework", pkg: "com.samsung.android.peripheral.framework" },
    { name: "Private Share", pkg: "com.samsung.android.privateshare" },
    { name: "Raja Ampat", pkg: "com.samsung.android.rajaampat" },
    { name: "Samsung Rampart", pkg: "com.samsung.android.rampart" },
    { name: "Customization Service", pkg: "com.samsung.android.rubin.app" },
    { name: "Samsung Pass", pkg: "com.samsung.android.samsungpass" },
    { name: "Samsung Pass Autofill", pkg: "com.samsung.android.samsungpassautofill" },
    { name: "Samsung Positioning", pkg: "com.samsung.android.samsungpositioning" },
    { name: "Samsung Cloud", pkg: "com.samsung.android.scloud" },
    { name: "Samsung SCPM", pkg: "com.samsung.android.scpm" },
    { name: "Samsung SCS", pkg: "com.samsung.android.scs" },
    { name: "Handwriting Service", pkg: "com.samsung.android.sdk.handwriting" },
    { name: "Samsung OCR", pkg: "com.samsung.android.sdk.ocr" },
    { name: "Professional Audio Utility", pkg: "com.samsung.android.sdk.professionalaudio.utility.jammonitor" },
    { name: "SDM Config", pkg: "com.samsung.android.sdm.config" },
    { name: "Security Log Agent", pkg: "com.samsung.android.securitylogagent" },
    { name: "Iris Server", pkg: "com.samsung.android.server.iris" },
    { name: "Live Drawing", pkg: "com.samsung.android.service.livedrawing" },
    { name: "People Stripe", pkg: "com.samsung.android.service.peoplestripe" },
    { name: "ST Platform", pkg: "com.samsung.android.service.stplatform" },
    { name: "Tag Service", pkg: "com.samsung.android.service.tagservice" },
    { name: "Samsung Travel", pkg: "com.samsung.android.service.travel" },
    { name: "Multi Sound Settings", pkg: "com.samsung.android.setting.multisound" },
    { name: "Shortcut Backup", pkg: "com.samsung.android.shortcutbackupservice" },
    { name: "Device Security (McAfee)", pkg: "com.samsung.android.sm.devicesecurity" },
    { name: "SM Policy", pkg: "com.samsung.android.sm.policy" },
    { name: "Smart Call Provider", pkg: "com.samsung.android.smartcallprovider" },
    { name: "Smart Face", pkg: "com.samsung.android.smartface" },
    { name: "Smart Fitting", pkg: "com.samsung.android.smartfitting" },
    { name: "Smart View", pkg: "com.samsung.android.smartmirroring" },
    { name: "Smart Suggestions", pkg: "com.samsung.android.smartsuggestions" },
    { name: "Smart Switch Assistant", pkg: "com.samsung.android.smartswitchassistant" },
    { name: "Samsung Pay", pkg: "com.samsung.android.spay" },
    { name: "Samsung Pay FW", pkg: "com.samsung.android.spayfw" },
    { name: "Samsung Pay Mini", pkg: "com.samsung.android.spaymini" },
    { name: "Samsung PDF Note", pkg: "com.samsung.android.spdfnote" },
    { name: "Samsung SSCO", pkg: "com.samsung.android.ssco" },
    { name: "Sticker Center", pkg: "com.samsung.android.stickercenter" },
    { name: "Sticker Plugin", pkg: "com.samsung.android.stickerplugin" },
    { name: "Mate Agent", pkg: "com.samsung.android.svcagent" },
    { name: "S Voice", pkg: "com.samsung.android.svoice" },
    { name: "Samsung Voice Input", pkg: "com.samsung.android.svoiceime" },
    { name: "TA Downloader", pkg: "com.samsung.android.tadownloader" },
    { name: "TA Auth Framework", pkg: "com.samsung.android.tapack.authfw" },
    { name: "Theme Center", pkg: "com.samsung.android.themecenter" },
    { name: "Theme Store", pkg: "com.samsung.android.themestore" },
    { name: "Trip Widget", pkg: "com.samsung.android.tripwidget" },
    { name: "Samsung TV Plus", pkg: "com.samsung.android.tvplus" },
    { name: "Ultra Data Saving", pkg: "com.samsung.android.uds" },
    { name: "Bixby Vision Apps", pkg: "com.samsung.android.visionarapps" },
    { name: "Bixby Vision Cloud Agent", pkg: "com.samsung.android.visioncloudagent" },
    { name: "Bixby Vision", pkg: "com.samsung.android.visionintelligence" },
    { name: "Bixby Vision Model", pkg: "com.samsung.android.vision.model" },
    { name: "Visual Cloud Core", pkg: "com.samsung.android.visual.cloudcore" },
    { name: "Visual ARs", pkg: "com.samsung.android.visualars" },
    { name: "Samsung Members", pkg: "com.samsung.android.voc" },
    { name: "Samsung Members Activity", pkg: "com.samsung.android.voc.LauncherActivity" },
    { name: "Voice Wakeup", pkg: "com.samsung.android.voicewakeup" },
    { name: "VT Camera Settings", pkg: "com.samsung.android.vtcamerasettings" },
    { name: "Digital Wellbeing (Samsung)", pkg: "com.samsung.android.wellbeing" },
    { name: "Yahoo Finance Edge", pkg: "com.samsung.android.widgetapp.yahooedge.finance" },
    { name: "Yahoo Sports Edge", pkg: "com.samsung.android.widgetapp.yahooedge.sport" },
    { name: "Highlight Player", pkg: "com.samsung.app.highlightplayer" },
    { name: "Video Trimmer", pkg: "com.samsung.app.newtrim" },
    { name: "CMH Agent", pkg: "com.samsung.cmh" },
    { name: "Auth Touch", pkg: "com.samsung.cmfa.AuthTouch" },
    { name: "Samsung Crane", pkg: "com.samsung.crane" },
    { name: "Daydream Customization", pkg: "com.samsung.daydream.customization" },
    { name: "DCM Service", pkg: "com.samsung.dcmservice" },
    { name: "Samsung DeX System UI", pkg: "com.samsung.desktopsystemui" },
    { name: "Samsung Discover", pkg: "com.samsung.discover" },
    { name: "Samsung E-Commerce", pkg: "com.samsung.ecomm" },
    { name: "Samsung E-Commerce (India)", pkg: "com.samsung.ecomm.global.in" },
    { name: "Samsung Enhance Service", pkg: "com.samsung.enhanceservice" },
    { name: "Face Service", pkg: "com.samsung.faceservice" },
    { name: "Fresco Logging", pkg: "com.samsung.fresco.logging" },
    { name: "GPUWatch", pkg: "com.samsung.gpuwatchapp" },
    { name: "Samsung Group Cast", pkg: "com.samsung.groupcast" },
    { name: "HS2.0 Provider", pkg: "com.samsung.hs20provider" },
    { name: "IP Service", pkg: "com.samsung.ipservice" },
    { name: "KLMS Agent", pkg: "com.samsung.klmsagent" },
    { name: "Knox Update Agent", pkg: "com.samsung.knox.appsupdateagent" },
    { name: "Knox Keychain", pkg: "com.samsung.knox.keychain" },
    { name: "Knox RCP Components", pkg: "com.samsung.knox.rcp.components" },
    { name: "Secure Folder", pkg: "com.samsung.knox.securefolder" },
    { name: "Secure Folder Setup", pkg: "com.samsung.knox.securefolder.setuppage" },
    { name: "Memory Saver", pkg: "com.samsung.memorysaver" },
    { name: "Samsung MLP", pkg: "com.samsung.mlp" },
    { name: "Pet Service", pkg: "com.samsung.petservice" },
    { name: "Samsung Calendar Provider", pkg: "com.samsung.providers.calendar" },
    { name: "Samsung RCS", pkg: "com.samsung.rcs" },
    { name: "Safety Information", pkg: "com.samsung.safetyinformation" },
    { name: "Samsung SOH Service", pkg: "com.samsung.sait.sohservice" },
    { name: "Samsung CSC", pkg: "com.samsung.sec.android.application.csc" },
    { name: "Teegris TUI Service", pkg: "com.samsung.sec.android.teegris.tui_service" },
    { name: "Samsung Sree", pkg: "com.samsung.sree" },
    { name: "Samsung SSU", pkg: "com.samsung.ssu" },
    { name: "Story Service", pkg: "com.samsung.storyservice" },
    { name: "S Voice Sync", pkg: "com.samsung.svoice.sync" },
    { name: "Bixby UI", pkg: "com.samsung.systemui.bixby" },
    { name: "Bixby UI v2", pkg: "com.samsung.systemui.bixby2" },
    { name: "Hide Notch", pkg: "com.samsung.systemui.hidenotch" },
    { name: "Hide Notch (No Round)", pkg: "com.samsung.systemui.hidenotch.withoutcornerround" },
    { name: "UCS Agent", pkg: "com.samsung.ucs.agent.ese" },
    { name: "Voice Service Platform", pkg: "com.samsung.voiceserviceplatform" },
    { name: "Auto Preconfig", pkg: "com.sec.android.AutoPreconfig" },
    { name: "Data Create", pkg: "com.sec.android.DataCreate" },
    { name: "Preconfig", pkg: "com.sec.android.Preconfig" },
    { name: "RIL Service Mode", pkg: "com.sec.android.RilServiceModeApp" },
    { name: "Samsung Setup Wizard", pkg: "com.sec.android.app.SecSetupWizard" },
    { name: "Smart Clip Edge", pkg: "com.sec.android.app.SmartClipEdgeService" },
    { name: "Samsung Apex", pkg: "com.sec.android.app.apex" },
    { name: "App Linker", pkg: "com.sec.android.app.applinker" },
    { name: "Samsung Billing", pkg: "com.sec.android.app.billing" },
    { name: "Bluetooth Test", pkg: "com.sec.android.app.bluetoothtest" },
    { name: "Chrome Customizations", pkg: "com.sec.android.app.chromecustomizations" },
    { name: "Samsung Clock", pkg: "com.sec.android.app.clockpackage" },
    { name: "DeX Launcher", pkg: "com.sec.android.app.desktoplauncher" },
    { name: "DeX on PC", pkg: "com.sec.android.app.dexonpc" },
    { name: "Factory Keystring", pkg: "com.sec.android.app.factorykeystring" },
    { name: "FM Radio", pkg: "com.sec.android.app.fm" },
    { name: "Game Hub", pkg: "com.sec.android.app.gamehub" },
    { name: "HW Module Test", pkg: "com.sec.android.app.hwmoduletest" },
    { name: "Samsung Kids Home", pkg: "com.sec.android.app.kidshome" },
    { name: "Magnifier", pkg: "com.sec.android.app.magnifier" },
    { name: "My Files", pkg: "com.sec.android.app.myfiles" },
    { name: "OCR", pkg: "com.sec.android.app.ocr" },
    { name: "Samsung Parser", pkg: "com.sec.android.app.parser" },
    { name: "Samsung Personalization", pkg: "com.sec.android.app.personalization" },
    { name: "Samsung Calculator", pkg: "com.sec.android.app.popupcalculator" },
    { name: "Quick Tool", pkg: "com.sec.android.app.quicktool" },
    { name: "Ringtone Backup", pkg: "com.sec.android.app.ringtoneBR" },
    { name: "Safety Assurance", pkg: "com.sec.android.app.safetyassurance" },
    { name: "Galaxy Store", pkg: "com.sec.android.app.samsungapps" },
    { name: "Samsung Internet", pkg: "com.sec.android.app.sbrowser" },
    { name: "Service Mode App", pkg: "com.sec.android.app.servicemodeapp" },
    { name: "Setup Wizard", pkg: "com.sec.android.app.setupwizard" },
    { name: "Setup Wizard Legal", pkg: "com.sec.android.app.setupwizardlegalprovider" },
    { name: "Samsung Health", pkg: "com.sec.android.app.shealth" },
    { name: "SoundAlive", pkg: "com.sec.android.app.soundalive" },
    { name: "SUW Script Player", pkg: "com.sec.android.app.suwscriptplayer" },
    { name: "SysScope", pkg: "com.sec.android.app.sysscope" },
    { name: "TF Unlock", pkg: "com.sec.android.app.tfunlock" },
    { name: "Tour Viewer", pkg: "com.sec.android.app.tourviewer" },
    { name: "Translator", pkg: "com.sec.android.app.translator" },
    { name: "Video Editor BGM", pkg: "com.sec.android.app.ve.vebgm" },
    { name: "Video Editor Preload", pkg: "com.sec.android.app.vepreload" },
    { name: "Voice Recorder", pkg: "com.sec.android.app.voicenote" },
    { name: "WFD Broker", pkg: "com.sec.android.app.wfdbroker" },
    { name: "Watch with TV", pkg: "com.sec.android.app.withtv" },
    { name: "WLAN Test", pkg: "com.sec.android.app.wlantest" },
    { name: "Auto Doodle", pkg: "com.sec.android.autodoodle.service" },
    { name: "LED Cover Service", pkg: "com.sec.android.cover.ledcover" },
    { name: "Weather Daemon", pkg: "com.sec.android.daemonapp" },
    { name: "DeX UI Service", pkg: "com.sec.android.desktopmode.uiservice" },
    { name: "DiagMon Agent", pkg: "com.sec.android.diagmonagent" },
    { name: "Smart Switch", pkg: "com.sec.android.easyMover" },
    { name: "Smart Switch Agent", pkg: "com.sec.android.easyMover.Agent" },
    { name: "One Hand Mode", pkg: "com.sec.android.easyonehand" },
    { name: "Emergency Launcher", pkg: "com.sec.android.emergencylauncher" },
    { name: "Emergency Mode Service", pkg: "com.sec.android.emergencymode.service" },
    { name: "AR Emoji Stickers (Alt)", pkg: "com.sec.android.mimage.avatar.stickers" },
    { name: "AR Emoji Stickers", pkg: "com.sec.android.mimage.avatarstickers" },
    { name: "Gear 360 Editor", pkg: "com.sec.android.mimage.gear360editor" },
    { name: "Photo Retouching", pkg: "com.sec.android.mimage.photoretouching" },
    { name: "OF Viewer", pkg: "com.sec.android.ofviewer" },
    { name: "OMC Service", pkg: "com.sec.android.omc" },
    { name: "Preload Installer", pkg: "com.sec.android.preloadinstaller" },
    { name: "Badge Provider", pkg: "com.sec.android.provider.badge" },
    { name: "Emergency Provider", pkg: "com.sec.android.provider.emergencymode" },
    { name: "S Note Provider", pkg: "com.sec.android.provider.snote" },
    { name: "Security Provider", pkg: "com.sec.android.providers.security" },
    { name: "Tasks Provider", pkg: "com.sec.android.providers.tasks" },
    { name: "SDHMS", pkg: "com.sec.android.sdhms" },
    { name: "Health Service", pkg: "com.sec.android.service.health" },
    { name: "SideSync 3.0", pkg: "com.sec.android.sidesync30" },
    { name: "Smart FPS Adjuster", pkg: "com.sec.android.smartfpsadjuster" },
    { name: "Split Sound", pkg: "com.sec.android.splitsound" },
    { name: "UIBC Virtual Softkey", pkg: "com.sec.android.uibcvirtualsoftkey" },
    { name: "S Memo Widget", pkg: "com.sec.android.widgetapp.diotek.smemo" },
    { name: "Favorite Contacts Widget", pkg: "com.sec.android.widgetapp.easymodecontactswidget" },
    { name: "Galaxy Store Widget", pkg: "com.sec.android.widgetapp.samsungapps" },
    { name: "Web Manual Widget", pkg: "com.sec.android.widgetapp.webmanual" },
    { name: "Transmit Power Service", pkg: "com.sec.app.TransmitPowerService" },
    { name: "Samsung Automation", pkg: "com.sec.automation" },
    { name: "BC Service", pkg: "com.sec.bcservice" },
    { name: "Downloadable Keystore", pkg: "com.sec.downloadablekeystore" },
    { name: "Knox Attestation (Enterprise)", pkg: "com.sec.enterprise.knox.attestation" },
    { name: "Knox Cloud MDM", pkg: "com.sec.enterprise.knox.cloudmdm.smdms" },
    { name: "SIM PIN Service", pkg: "com.sec.enterprise.mdm.services.simpin" },
    { name: "MDM VPN Service", pkg: "com.sec.enterprise.mdm.vpn" },
    { name: "ePDG Test App", pkg: "com.sec.epdgtestapp" },
    { name: "Everglades", pkg: "com.sec.everglades" },
    { name: "Everglades Update", pkg: "com.sec.everglades.update" },
    { name: "Samsung Factory", pkg: "com.sec.factory" },
    { name: "Factory Camera", pkg: "com.sec.factory.camera" },
    { name: "Iris User Camera", pkg: "com.sec.factory.iris.usercamera" },
    { name: "Hearing Adjust", pkg: "com.sec.hearingadjust" },
    { name: "Kids Installer (Alt)", pkg: "com.sec.kidsplat.installer" },
    { name: "Folder Container", pkg: "com.sec.knox.foldercontainer" },
    { name: "Knox Setup Wizard", pkg: "com.sec.knox.knoxsetupwizardclient" },
    { name: "Knox Switcher", pkg: "com.sec.knox.switcher" },
    { name: "NSFLP Location", pkg: "com.sec.location.nsflp2" },
    { name: "Smart Tethering", pkg: "com.sec.mhs.smarttethering" },
    { name: "MLDAP Checker", pkg: "com.sec.mldapchecker" },
    { name: "Modem Settings", pkg: "com.sec.modem.settings" },
    { name: "PENUP", pkg: "com.sec.penup" },
    { name: "Assisted Dialing Provider", pkg: "com.sec.providers.assisteddialing" },
    { name: "Readers Hub", pkg: "com.sec.readershub" },
    { name: "Galaxy Store Widget (Alt)", pkg: "com.sec.samsung.android.widgetapp.samsungapps" },
    { name: "SmartCard Manager", pkg: "com.sec.smartcard.manager" },
    { name: "Flash Annotate", pkg: "com.sec.spen.flashannotate" },
    { name: "Samsung Push Service", pkg: "com.sec.spp.push" },
    { name: "Secondary Video Engine", pkg: "com.sec.sve" },
    { name: "Unified Wi-Fi Calling", pkg: "com.sec.unifiedwfc" },
    { name: "USB Settings", pkg: "com.sec.usbsettings" },
    { name: "VoWiFi SPG", pkg: "com.sec.vowifispg" },
    { name: "NSDSWebApp", pkg: "com.sec.vsim.ericssonnsds.webapp" },
    { name: "Yosemite Phone", pkg: "com.sec.yosemite.phone" },
    { name: "Factory App (Sem)", pkg: "com.sem.factoryapp" },
    { name: "My Singtel", pkg: "com.singtel.mysingtel" },
    { name: "SKMS Agent", pkg: "com.skms.android.agent" },
    { name: "Skype", pkg: "com.skype.raider" },
    { name: "Snapchat Camera Kit", pkg: "com.snap.camerakit.plugin.v1" },
    { name: "Snapchat", pkg: "com.snapchat.android" },
    { name: "Indramayu", pkg: "com.srin.indramayu" },
    { name: "LTE Functionality Test", pkg: "com.test.LTEfunctionality" },
    { name: "SwiftKey Keyboard", pkg: "com.touchtype.swiftkey" },
    { name: "TripAdvisor", pkg: "com.tripadvisor.tripadvisor" },
    { name: "Trustonic TUI Service", pkg: "com.trustonic.tuiservice" },
    { name: "Peel Smart Remote", pkg: "com.tv.peel.samsung.app" },
    { name: "Vlingo Midas", pkg: "com.vlingo.midas" },
    { name: "WOMA Config (Alt)", pkg: "com.wsomacp" },
    { name: "WSSNPS", pkg: "com.wssnps" },
    { name: "Yandex Browser", pkg: "com.yandex.browser" },
    { name: "Yelp Edge Panel", pkg: "com.yelp.android.samsungedge" },
    { name: "Samsung Zeropage", pkg: "de.axelspringer.yana.zeropage" },
    { name: "Flipboard Briefing", pkg: "flipboard.boxer.app" },
    { name: "Amazon Shopping", pkg: "in.amazon.mShop.android.shopping" },
    { name: "Yandex Disk", pkg: "ru.yandex.disk" },
    { name: "Yandex Search", pkg: "ru.yandex.searchplugin" },
    { name: "Yandex Maps", pkg: "ru.yandex.yandexmaps" }
];


